config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  post '/' => 'welcome#create'
  get '/positions' => 'positions#index'
  get '/positions/:id' => 'positions#show'
  get '/team_listing'  => 'ffn#cities'
  get '/names/listing' => 'ffn#listing'
  get '/info'          => 'ffn#info'

  resources :positions
  resources :names
  resources :byes
  resources :rankings
  resources :teams
  resources :weather
  resources :ffn
end

app/models/bye.rb
class Bye < ActiveRecord::Base
end

app/models/ffn_api.rb
require 'httparty'

module FfnApi
	# include FFNerd
	def self.teams_by_name(team_nickname)
		# team_name = URI.encode(team_nickname)
		url = "http://www.fantasyfootballnerd.com/service/nfl-teams/json/he96q9pfk242"
		response = HTTParty.get(url)
		JSON.parse(response.body)
		teams_array = response['NFLTeams'].each_with_index { |i| print i['shortName'] + ' ' }
		teams_array
	end

	def self.players_by_name(full_name)
		position = URI.encode(full_name)
		url = "http://www.fantasyfootballnerd.com/service/players/json/he96q9pfk242/#{position}"
		response = HTTParty.get(url)
		JSON.parse(response.body)
		players_array = response['Players'].each_with_index { |i| print i['displayName'] + ' ' }
		players_array
	end
end

app/models/name.rb
class Name < ActiveRecord::Base
end

app/models/position.rb
class Position < ActiveRecord::Base
end

app/models/team.rb
class Team < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/byes_controller.rb
class ByesController < ApplicationController
end

app/controllers/ffn_controller.rb
class FfnController < ApplicationController
	def index	
	end

	def cities
		#team search
		@team_nickname = params[:short_name]
		@teams = FfnApi.teams_by_name(@team_nickname)
		@team_list = []
		@teams.each { |team| @team_list << { team: team['shortName']} }
		@team_list
	end

	def listing
		#player search by position
		@player_fullname = params[:position]
		@players = FfnApi.players_by_name(@player_fullname)
		@player_list = []
		@players.each_with_index { |player| @player_list << { player: player['displayName']} }
		@player_list
	end

	def info
		#team search
		@team_nickname = params[:short_name]
		@teams = FfnApi.teams_by_name(@team_nickname)
		@team_list = []
		@teams.each { |team| @team_list << { team: team['shortName']} }
		@team_list

		#player search by position
		@player_fullname = params[:position]
		@players = FfnApi.players_by_name(@player_fullname)
		@player_list = []
		@players.each_with_index { |player| @player_list << { player: player['displayName']} }
		@player_list

		
	end
end

app/controllers/names_controller.rb
class NamesController < ApplicationController
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
	def index
		@positions = Position.all
	end

	def show
		@position = Position.find(params[:id]) 
	end

	def new
		@position = Position.new	
	end

	def create
		position = Position.create(position_params)
		position.save
		redirect_to 'positions/:id'
	end

	def destroy
		Location.destroy(params[:id])
		redirect_to positions_path
	end

	def edit
		position = Position.find(params[:id])
		position.update(position_params)
		redirect_to position
	end

	def position_params
		params.require(:position).permit(
			:position
			)
	end
	
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def welcome
		
	end

	def index
		@positions = Position.all
		@teams = Team.all
	end

	def show
		@position = Position.find(params[:id]) 
		@team = Team.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dissembly_api_helper.rb
module DissemblyApiHelper
  BASE_URI = 'http://www.fantasyfootballnerd.com/service'

  def self.root_path
  	BASE_URI
  end

  def self.get(serviceName)
  	HTTParty.get(root_path + "/#{serviceName}")[serviceName.split('/').last]
  end
 
  def self.get_serviceName(name, hash)
  	serviceNames = get(name).map do |serviceName|
  		symbolify serviceName
  	end
  	hash ? hashify(serviceNames) : serviceNames
  end
  
  def self.set_format(format="json")
  	@@format = "/#{format}"
  end
  set_format = "json"

  def self.set_num(num="he96q9pfk242")
  	@@num = "/#{num}"
  end
  set_num "he96q9pfk242"


# SERVICE_NAMES

	def self.nfl_teams(hash=false)
		get_serviceName "nfl-teams", hash	
	end

	def self.players(hash=false)
		get_serviceName "players", hash	
	end

	def self.byes(hash=false)
		get_serviceName "byes", hash	
	end

	def self.draft_rankings(hash=false)
		get_serviceName "draft-rankings", hash	
	end

	def self.draft_projections(hash=false)
		get_serviceName "draft-projections", hash	
	end

	def self.players(hash=false)
		get_serviceName "players", hash	
	end


end

app/views/ffn/cities.html.erb
<div class='header'>
	<header><strong>NFL Cities</strong>
		<% @team_list.each do |team| %>
			<li>
				<%= team.first[1] %>
			</li>
		<% end %>

		<% %>
		<% %>

		</br>
	</header>
</div>

app/views/ffn/info.html.erb
<div class='header'>
	<header><strong>NFL Cities</strong>
		<% @team_list.each do |team| %>
			<li>
				<%= team.first[1] %>
			</li>
		<% end %>

		<% %>
		<% %>

		</br>
	</header>
</div>

</br></br>

<div>
	<% @player_list.each do |player| %>
		<li>
			<%= player.first[1] %>
		</li>
	<% end %>
</div>

app/views/ffn/listing.html.erb
<%#= @player_fullname %>

<% @player_list.each do |player| %>
	<li>
		<%= player.first[1] %>
	</li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DebarbieriFfApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/positions/index.html.erb
<%= @players %>

<%# @player_list.each do |player| %>
		<!-- <li><a href="<%#= position_path(position) %>"><%#= position.position.upcase %></a></li> -->
			<li>
				<%#= player.first[1] %>
			</li>
<%# end %>

app/views/positions/show.html.erb
<%#= @position.position.upcase! %>

app/views/welcome/index.html.erb
<div class='home'>
	<header class="header">
		<h1 class='title'>Mike D.'s Fantasy Football Picks</h1></header></br>

	<h3 class='subtitle'></h3>
		<%= form_tag "/names/listing", :method => :get do %>
			<p><%= text_field_tag(:position, nil, { placeholder: "QB, RB, WR, TE, K, DEF" }) %></p>
				<%= submit_tag 'Search' %>
		<% end %>

		<a href="/team_listing">NFL Cities</a>

</div>